export const countries = [
  { label: "AF", name: "Afghanistan", value: "+93" },
  { label: "AL", name: "Albania", value: "+355" },
  { label: "DZ", name: "Algeria", value: "+213" },
  { label: "AD", name: "Andorra", value: "+376" },
  { label: "AO", name: "Angola", value: "+244" },
  { label: "AR", name: "Argentina", value: "+54" },
  { label: "AM", name: "Armenia", value: "+374" },
  { label: "AU", name: "Australia", value: "+61" },
  { label: "AT", name: "Austria", value: "+43" },
  { label: "AZ", name: "Azerbaijan", value: "+994" },
  { label: "BH", name: "Bahrain", value: "+973" },
  { label: "BD", name: "Bangladesh", value: "+880" },
  { label: "BY", name: "Belarus", value: "+375" },
  { label: "BE", name: "Belgium", value: "+32" },
  { label: "BJ", name: "Benin", value: "+229" },
  { label: "BT", name: "Bhutan", value: "+975" },
  { label: "BO", name: "Bolivia", value: "+591" },
  { label: "BR", name: "Brazil", value: "+55" },
  { label: "BG", name: "Bulgaria", value: "+359" },
  { label: "CA", name: "Canada", value: "+1" },
  { label: "CN", name: "China", value: "+86" },
  { label: "CO", name: "Colombia", value: "+57" },
  { label: "CU", name: "Cuba", value: "+53" },
  { label: "CZ", name: "Czech Republic", value: "+420" },
  { label: "DK", name: "Denmark", value: "+45" },
  { label: "EG", name: "Egypt", value: "+20" },
  { label: "FR", name: "France", value: "+33" },
  { label: "DE", name: "Germany", value: "+49" },
  { label: "GR", name: "Greece", value: "+30" },
  { label: "IN", name: "India", value: "+91" },
  { label: "ID", name: "Indonesia", value: "+62" },
  { label: "IR", name: "Iran", value: "+98" },
  { label: "IQ", name: "Iraq", value: "+964" },
  { label: "IE", name: "Ireland", value: "+353" },
  { label: "IT", name: "Italy", value: "+39" },
  { label: "JP", name: "Japan", value: "+81" },
  { label: "KE", name: "Kenya", value: "+254" },
  { label: "MX", name: "Mexico", value: "+52" },
  { label: "MY", name: "Malaysia", value: "+60" },
  { label: "NL", name: "Netherlands", value: "+31" },
  { label: "NZ", name: "New Zealand", value: "+64" },
  { label: "NG", name: "Nigeria", value: "+234" },
  { label: "NO", name: "Norway", value: "+47" },
  { label: "PK", name: "Pakistan", value: "+92" },
  { label: "PH", name: "Philippines", value: "+63" },
  { label: "PL", name: "Poland", value: "+48" },
  { label: "PT", name: "Portugal", value: "+351" },
  { label: "QA", name: "Qatar", value: "+974" },
  { label: "RU", name: "Russia", value: "+7" },
  { label: "SA", name: "Saudi Arabia", value: "+966" },
  { label: "SG", name: "Singapore", value: "+65" },
  { label: "ZA", name: "South Africa", value: "+27" },
  { label: "ES", name: "Spain", value: "+34" },
  { label: "SE", name: "Sweden", value: "+46" },
  { label: "CH", name: "Switzerland", value: "+41" },
  { label: "TH", name: "Thailand", value: "+66" },
  { label: "TR", name: "Turkey", value: "+90" },
  { label: "UA", name: "Ukraine", value: "+380" },
  { label: "AE", name: "United Arab Emirates", value: "+971" },
  { label: "GB", name: "United Kingdom", value: "+44" },
  { label: "US", name: "United States", value: "+1" },
  { label: "VN", name: "Vietnam", value: "+84" },
  { label: "YE", name: "Yemen", value: "+967" },
  { label: "ZW", name: "Zimbabwe", value: "+263" },
];

export const COUNTRIES_OPTIONS = [
  { label: "United Kingdom", value: "UK" },
  { label: "United States", value: "US" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
  { label: "Germany", value: "DE" },
  { label: "France", value: "FR" },
  { label: "Spain", value: "ES" },
  { label: "Italy", value: "IT" },
  { label: "Netherlands", value: "NL" },
  { label: "Sweden", value: "SE" },
  { label: "Switzerland", value: "CH" },
  { label: "Brazil", value: "BR" },
  { label: "India", value: "IN" },
  { label: "China", value: "CN" },
  { label: "Japan", value: "JP" },
  { label: "South Korea", value: "KR" },
  { label: "Mexico", value: "MX" },
  { label: "South Africa", value: "ZA" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Singapore", value: "SG" },
  { label: "New Zealand", value: "NZ" },
];
